language: node_js
sudo: false
node_js:
- '4.2'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: "oWSPUNVPpIWZMZ6DGXScx5AaiUHSso5nz/Kk0xTciMJlGsS57XSjFKUfdsqqQ7Wsw+W2oZchYgI+EYWEUX4nG9PnJIhmN0m7sGJlPxmTyQf07H0q+x6Z0/l6PE81AaUhrUX1ESGfooGhnj+g+TbELiI8LCALPAqJWgoPJ6ufYnk="
  on:
    tags: true
    repo: flowbased/fbp
