language: node_js
sudo: false
node_js:
- '6'
before_script:
- npm install -g grunt-cli
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: "f8HCo++sboU3FUuYLmKC3tCIH9WEyJbjItCFDXCAOaBTuwWJYxtp+ehOxPsewX78SwO9LHXIH/O8bUqQgd/kiQA6umcbNQ1OI636NaQQXDNKP4Mdy+hSghwwtrc2iMs2JkcdWg681f8JBQt8L3jopXM29e+aQ1NPtZByiEgmrLM="
  on:
    tags: true
    repo: flowbased/fbp
